apiVersion: v1
kind: Secret
metadata:
  name: {{ template "affiliates.fullname" . }}
  labels:
    app: {{ template "affiliates.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sa-password: {{ default "" .Values.dbSApassword | b64enc | quote }}
